### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ozone521** [foamliu/Super-Resolution-Net#1]
(tensorflow) E:\chrome downloads\Super-Resolution-Net>python train.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    scale = int(args["scale"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by ozone521** [comment]
how can I run this code successfully?

**Comment by foamliu** [comment]
Seems you need to specify an scale as argument.
